### PR TITLE
40 feature spinner when data pending chekurkov

### PR DESCRIPTION
**Pull request by Dmitry528**
I create only spinner component.

### CODE REVIEW

**Comment by Dmitry528** [comment]
> I create only spinner component.

1) Firstly add to state "Loading: true"
2) Second when your data is loaded, use setState(({loading: false}))

**Review by AndriiDruzhytskyi — APPROVED** [review]
All works great.

**Review by victorpoliushko — APPROVED** [review]
Advice: leave new line at end of files

**Review by Viktor-Hordynskyi — APPROVED** [review]
Good job)

**Pull request merged**
