### PR TITLE
87 feature add uload images preview druzhytskii

### PR DESCRIPTION
**Pull request by AndriiDruzhytskyi**
Test upload images preview.
Dont forget to create uploads folder on the server if you use Linux.

### CODE REVIEW

**Review by marrybbb — COMMENTED** [review]
beauiful prewiev
image

**Review by andrii-kondratiuk — COMMENTED** [review]
awesome preview feature, both as small and large preview!

**Review by Dmitry528 — APPROVED** [review]
Nice design, good work

**Comment by AndriiDruzhytskyi** [comment]
> awesome preview feature, both as small and large preview!
> The only issue I have: you can't preview .txt files when its format changed to .png or .jpg
> Screenshot from 2019-12-07 11-50-21

Fixed.

**Review by andrii-kondratiuk — APPROVED** [review]

**Review by marrybbb — APPROVED** [review]

**Pull request merged**
