### PR TITLE
31 feature slider chekurkov

### PR DESCRIPTION
**Pull request by Dmitry528**
Slider on Single Place

### CODE REVIEW

**Review by victorpoliushko — COMMENTED** [review]
fix photo sizes

**Review by victorpoliushko — APPROVED** [review]
gj

**Review by Viktor-Hordynskyi — COMMENTED** [review]
Pls, add a container for your image, and assure that all your images have right sizes (don't stretch an image)

**Review by AndriiDruzhytskyi — APPROVED** [review]
All works good.

**Review by Viktor-Hordynskyi — APPROVED** [review]

**Pull request merged**
